name: Sarthi Preview Environments
on:
  pull_request:
    types: [ opened, closed, reopened, synchronize ]
  push:
  # delete preview environments when branches are deleted
  delete:

jobs:
  sarthi_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Sarthi
        uses: tushar5526/sarthi-deploy@delete-preview
        with:
          compose_file: docker-compose.yml # override this with the compose file name
          sarthi_server_url: 'http://13.239.136.214:5000'
          sarthi_secret: 'KZ9UVsfT7D6KXQs3hxUu4hjSWV5wlMXmDJu5xMAkzvM=' # Secret text generate while setting up the server
